package com.example.jetgames.core.remote.model.games

data class GameDto(
    val added: Int? = null,
    val added_by_status: AddedByStatusDto? = null,
    val background_image: String? = null,
    val clip: Any? = null,
    val dominant_color: String? = null,
    val esrb_rating: EsrbRatingDto? = null,
    val genres: List<GenreDto>? = null,
    val id: Int? = null,
    val metacritic: Int? = null,
    val name: String? = null,
    val parent_platforms: List<ParentPlatformDto>? = null,
    val platforms: List<PlatformXDto>? = null ,
    val playtime: Int? = null ,
    val rating: Double? = null ,
    val rating_top: Int? = null ,
    val ratings: List<RatingDto>? = null,
    val ratings_count: Int? = null,
    val released: String? = null ,
    val reviews_count: Int? = null,
    val reviews_text_count: Int? = null,
    val saturated_color: String? = null,
    val short_screenshots: List<ShortScreenshotDto>? = null,
    val slug: String? = null,
    val stores: List<StoreDto>? = null,
    val suggestions_count: Int? = null,
    val tags: List<TagDto>? = null,
    val tba: Boolean? = null ,
    val updated: String? = null ,
    val user_game: Any? = null
)