package com.example.jetgames.core.remote.model.details

import com.example.jetgames.core.remote.model.games.*

data class GameDetailsDto(
    val achievements_count: Int? = null,
    val added: Int? = null,
    val added_by_status: AddedByStatusDto? = null,
    val additions_count: Int? = null,
    val alternative_names: List<String>? = null,
    val background_image: String? = null,
    val background_image_additional: String? = null,
    val creators_count: Int? = null,
    val description: String? = null,
    val description_raw: String? = null,
    val dominant_color: String? = null,
    val esrb_rating: EsrbRatingDto? = null,
    val game_series_count: Int? = null,
    val genres: List<GenreDto>? = null,
    val id: Int? = null,
    val metacritic: Int? = null,
    val metacritic_platforms: List<MetacriticPlatformDto>? = null,
    val metacritic_url: String? = null,
    val movies_count: Int? = null,
    val name: String? = null,
    val name_original: String? = null,
    val parent_achievements_count: Int? = null,
    val parent_platforms: List<ParentPlatformDto>? = null,
    val parents_count: Int? = null,
    val playtime: Int? = null,
    val rating: Double? = null,
    val rating_top: Int? = null,
    val ratings: List<RatingDto>? = null,
    val ratings_count: Int? = null,
    val reddit_count: Int? = null,
    val reddit_description: String? = null,
    val reddit_logo: String? = null,
    val reddit_name: String? = null,
    val reddit_url: String? = null,
    val released: String? = null,
    val reviews_count: Int? = null,
    val reviews_text_count: Int? = null,
    val saturated_color: String? = null,
    val screenshots_count: Int? = null,
    val slug: String? = null,
    val stores: List<StoreDto>? = null,
    val suggestions_count: Int? = null,
    val tags: List<TagDto>? = null,
    val tba: Boolean? = null,
    val twitch_count: Int? = null,
    val updated: String? = null,
    val website: String? = null,
    val youtube_count: Int? = null,
)