package com.example.jetgames.core.remote.model.details

import com.example.jetgames.core.remote.model.games.*

data class GameDetailsDto(
    val achievements_count: Int,
    val added: Int,
    val added_by_status: AddedByStatusDto,
    val additions_count: Int,
    val alternative_names: List<String>,
    val background_image: String,
    val background_image_additional: String,
    val creators_count: Int,
    val description: String,
    val description_raw: String,
    val dominant_color: String,
    val esrb_rating: EsrbRatingDto,
    val game_series_count: Int,
    val genres: List<GenreDto>,
    val id: Int,
    val metacritic: Int,
    val metacritic_platforms: List<MetacriticPlatformDto>,
    val metacritic_url: String,
    val movies_count: Int,
    val name: String,
    val name_original: String,
    val parent_achievements_count: Int,
    val parent_platforms: List<ParentPlatformDto>,
    val parents_count: Int,
    val playtime: Int,
    val rating: Double,
    val rating_top: Int,
    val ratings: List<RatingDto>,
    val ratings_count: Int,
    val reddit_count: Int,
    val reddit_description: String,
    val reddit_logo: String,
    val reddit_name: String,
    val reddit_url: String,
    val released: String,
    val reviews_count: Int,
    val reviews_text_count: Int,
    val saturated_color: String,
    val screenshots_count: Int,
    val slug: String,
    val stores: List<StoreDto>,
    val suggestions_count: Int,
    val tags: List<TagDto>,
    val tba: Boolean,
    val twitch_count: Int,
    val updated: String,
    val website: String,
    val youtube_count: Int,
)